---
title: "Laboratorio1"
author: "Javier Alejandro Mazaiegos Godoy"
date: "2022-08-03"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Librerias}
library(readxl)
library(dplyr)
library(stringr)
library(readr)
```

## Problema 1

En la siguiente tabla sobre las entregas del año 2018 se puede ver 9 variables y 2,180 observaciones.

```{r Archivos y columa}
archivos = list.files(pattern="*.xlsx")
concatenacion <- function(x){
  return( cbind(read_excel(toString(x)),str_replace(x,".xlsx","")) )
  }

tabla <- sapply(archivos, concatenacion) %>% bind_rows() %>% rename_with(~ c('Fecha'), 9)
tabla <- subset(tabla, select = -c(TIPO,...10))
(tabla)

```

```{r Exportar excel}
write_excel_csv2(tabla,"Embotelladora_nacional_entregas_2018.xls",delim = ",")
```

## Problema 2

```{r moda}

moda <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
   
}

generador <- function(i, tamaño){
  vector_1 <- sample(i, size = tamaño, replace = TRUE)
  
  return(
   vector_1
  )}

moda_vectores = lapply(lapply(list(letters[1:27],c(FALSE,TRUE),c("a", "b", "c")), generador, 20), moda)

(moda_vectores)
```

## Problema 3

En la tabla siguiente tabla sobre el parque vehicular de Enero de 2019 se pueden ver 10 variables y 2,435,294 observaciones

```{r Parque vehicular}
library(readr)
Parque_vehicular <- read_delim('INE_PARQUE_VEHICULAR_080219.txt', delim="|",show_col_types = FALSE , col_types = cols(
  ANIO_ALZA = col_double(),
  MES = col_character(),
  NOMBRE_DEPARTAMENTO = col_character(),
  NOMBRE_MUNICIPIO = col_character(),
  MODELO_VEHICULO = col_character(),
  LINEA_VEHICULO = col_character(),
  TIPO_VEHICULO = col_character(),
  USO_VEHICULO = col_character(),
  MARCA_VEHICULO = col_character(),
  CANTIDAD = col_double(),
  ...11 = col_skip()))

(Parque_vehicular)
```
